template-repository: "jebel-quant/rhiza"
template-branch: "main"
include:
    - .github
    - tests
    - .editorconfig
    - .gitignore
    - .pre-commit-config.yaml
    - CODE_OF_CONDUCT.md
    - CONTRIBUTING.md
    - Makefile
    - pytest.ini
    - LICENSE
    - presentation
    - book
exclude:
    - .github/workflows/docker.yml
    - .github/workflows/devcontainer.yml
    - ruff.toml
