#!/bin/sh
# Script to update README.md with the current output from `make help`
#
# This script replaces the hardcoded Makefile help output in README.md
# with the actual output generated by running `make help`.

set -eu

# Navigate to repository root
cd "$(dirname "$0")/../.."

README_FILE="README.md"
TEMP_FILE=$(mktemp)
HELP_TEMP=$(mktemp)

# Generate the help output from Makefile
# Strip ANSI color codes and filter out make[1] directory messages
make help 2>/dev/null | \
    sed 's/\x1b\[[0-9;]*m//g' | \
    grep -v "^make\[" | \
    grep -v "Entering directory" | \
    grep -v "Leaving directory" > "$HELP_TEMP"

# Create the new README with updated help output
# Using a temporary file to avoid awk escaping issues
awk -v helpfile="$HELP_TEMP" '
BEGIN {
    in_help_block = 0
    pattern_found = 0
}

# Detect start of help output block
/^Run `make help` to see all available targets:$/ {
    print
    pattern_found = 1
    getline
    if ($0 == "") {
        print
    }
    getline
    if ($0 ~ /^```makefile$/) {
        print "```makefile"
        # Read and print help output from file
        while ((getline line < helpfile) > 0) {
            print line
        }
        close(helpfile)
        in_help_block = 1
        next
    }
}

# Skip lines inside the old help block
in_help_block == 1 && /^```$/ {
    print "```"
    in_help_block = 0
    next
}

in_help_block == 1 {
    next
}

# Print all other lines
{
    print
}

END {
    if (pattern_found == 0) {
        print "ERROR: Could not find help section marker in README.md" > "/dev/stderr"
        exit 1
    }
}
' "$README_FILE" > "$TEMP_FILE"

# Check if awk succeeded
if [ $? -ne 0 ]; then
    rm -f "$TEMP_FILE" "$HELP_TEMP"
    echo "ERROR: Failed to update README.md" >&2
    exit 1
fi

# Replace the original README with the updated version
mv "$TEMP_FILE" "$README_FILE"

# Clean up temporary help file
rm -f "$HELP_TEMP"

echo "README.md updated with current 'make help' output"
