name: 'Configure Git Auth for Private Packages'
description: 'Configure git to use token authentication for private GitHub packages'

inputs:
  token:
    description: 'GitHub token to use for authentication (use github.token)'
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Configure git authentication
      shell: bash
      run: |
        # Configure git to use token authentication for GitHub URLs
        # This allows uv/pip to install private packages from GitHub
        git config --global url."https://${{ inputs.token }}@github.com/".insteadOf "https://github.com/"

        echo "✓ Git configured to use token authentication for GitHub"
